### ISSUE TITLE
Question: Possible to embed the editors as part of an application?

### ISSUE THREAD

**Issue by zakaluka** [kiegroup/kogito-online#8]
Hello,

Is it possible to embed the BPMN and DMN editors as part of an application?  Basically having the ability to operate within a protected environment, with access to authorized users only and working with a single set of BPMN and DMN files?

If this is the wrong place to ask this question, please let me know where I should go.

Thank you.

**Comment by ederign** [comment]
Hi @zakaluka sorry for the delay on this, the right repo for this is [kogito-tooling](https://github.com/kiegroup/kogito-tooling)! :)

But yes, it is possible, take a loot at:

https://blog.kie.org/2020/10/bpmn-and-dmn-standalone-editors.html


If you need any further help feel free to reach us on kogito tooling repo.
